### ISSUE TITLE
[PHP 7.0] update phenx/php-svg-lib

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#1472]
Looks like the PHP SVG Library is causing incompatibility with PHP 7.0+:
`
Fatal error: Cannot use Sabberworm\CSS\Value\String as String because 'String' is a special class name
`
It looks like current master branch of `phenx/php-svg-lib` has updated `sabberworm/php-css-parser` requirement which fixes this, but this hasn't been released yet.
@PhenX could you publish a release and update the requirement for dompdf too?

Thanks!

**Comment by maps82** [comment]
Dompdf is essentially not working on PHP7 and the problem is easy to fix. It would be very appreciated to release a new version of the svg lib and update dompdf.

**Comment by Spreeuw** [comment]
@maps82 I fixed this for my own integration by setting a higher version of phenx/php-svg-lib in my composer.json:
``` js
{
  "require": {
    "php": ">=5.3.0",
    "dompdf/dompdf": "*",
    "phenx/php-svg-lib": "dev-master as 0.2"
  }
}
```

**Comment by maps82** [comment]
Thanks for sharing that quick fix!

**Comment by PhenX** [comment]
Hello I just published a new release (v0.3) for php-svg-lib

**Comment by Spreeuw** [comment]
Thanks @PhenX! 👍  Perhaps reopen the issue until dompdf has updated the requirement in composer.json too though?

**Comment by PhenX** [comment]
Yep, you are right

**Comment by bsweeney** [comment]
Addressed in commit c2b6f04.

**Comment by tucson-tom** [comment]
I just pulled fresh (today) from Composer in a new project and this issue still seems to be relevant.  Two fatal errors in the version of Sabberworm that Composer decided to pul down:

```
Fatal error: Cannot use Sabberworm\CSS\Value\String as String because 'String' is a special class name in C:\TEMP\backup\php-decomposer-master\projects\dompdf\staging\vendor\sabberworm\php-css-parser\lib\Sabberworm\CSS\Parser.php on line 20

Fatal error: Cannot use 'String' as class name as it is reserved in C:\TEMP\backup\php-decomposer-master\projects\dompdf\staging\vendor\sabberworm\php-css-parser\lib\Sabberworm\CSS\Value\String.php on line 5

```

These lint issues were discovered while decomposing dompdf.
