### ISSUE TITLE
Image Rendering Issue 

### ISSUE THREAD

**Issue by KvRae** [dompdf/dompdf#2965]
Greetings everyone, so I'm working on a local server and I want to render an image of a  logo on the top but it seems to be not loading properly
here is what I get 
![issue](https://user-images.githubusercontent.com/58667227/181517285-128414ea-7170-4875-a38a-b9d0543ec746.jpeg)
and that's the code (twig)
![code](https://user-images.githubusercontent.com/58667227/181518712-e5370599-330e-46c7-94aa-1a8bdaeb6359.png)
 here is the controller function that renders the pdf
![Controller](https://user-images.githubusercontent.com/58667227/181519634-b67ca7a2-8eb0-4a95-b4c2-979fbc7aa524.png)
Thanks for responding

**Comment by bsweeney** [comment]
There are two things to consider in your current setup.
1. Since you're not loading an actual file Dompdf attempts to read the image relative to the PHP document if the path is relative (i.e. starts without a "/"). If the path is absolute (e.g. starts with a "/") Dompdf will attempt to read the file from the root of the filesystem. I don't know what path `asset` generates, so that would help determine what's going on.
2. Dompdf has some basic protections in place to prevent loading random files from the filesystem. To allow filesystem resources you have to specify the allowed paths by including them in the chroot option.

**Comment by KvRae** [comment]
So can you give me an example on how to load an image file into dmopdf ? what is the path that I should make into the <img src=""> tag here is my project tree
![tree](https://user-images.githubusercontent.com/58667227/181529004-8a2a4b35-aeb5-4508-bb2b-655cc98cfd70.png)

**Comment by bsweeney** [comment]
For that structure, an absolute path would be "/public/assets/img/Logo_tt.jpg" and you would need to configure chroot to allow, for example, "/public/assets"

**Comment by KvRae** [comment]
Thanks, it works

**Comment by KvRae** [comment]
Ops ,

**Comment by KvRae** [comment]
Sorry, it didn't work on the rendered pdf, ti guess i have an issue with the chroot option 
![hello](https://user-images.githubusercontent.com/58667227/181568549-f2c6a249-4f71-40a6-b72a-e5fcb7fe71f8.png)
is this the correct way to do it?
![Chroot](https://user-images.githubusercontent.com/58667227/181570095-53b0939d-f1e0-45fa-b3fd-42c992e96488.png)
 I'm sorry again

**Comment by bsweeney** [comment]
You'll want to pass the options to the constructor:

```
$pdfOptions = new Options();
$pdfOptions->setChroot("/public/assets");
$this->domPdf = new Dompdf($pdfOptions);
```

or, more simply:

```
$this->domPdf = new Dompdf(["chroot" => ["/public/assets"]]);
```

**Comment by KvRae** [comment]
Sir, I'm so sorry, it didn't work both ways 😢do you know any guide on how to do it, I don't want to waste your valuable time
![Screenshot 2022-07-28 162126](https://user-images.githubusercontent.com/58667227/181575653-d407eb81-e21c-433d-93fe-1dd5f7d6a4a4.png)
same issue: Image not found or type unknown

**Comment by KvRae** [comment]
did that already and I tried another solution by replacing the img src="http://127.0.0.1:8000/assets/img/Logo_tt.png"  and adding  $pdfOptions->isRemoteEnabled(true);
still the same problem 😢

**Comment by bsweeney** [comment]
For remote images you might also need to set the appropriate temporary directory. Also make sure the GD extension for PHP is loaded since you're using a PNG. You can minimize the variables by using a JPG, which requires no processing.

Also, if you're able to use the debugging configuration you should be able to get more details messaging in the logs as to why you're having issues.

**Comment by KvRae** [comment]
I turned it into jpg, what's the thing about the temporary directory you've mentioned sorry?

**Comment by bsweeney** [comment]
There is an option to specify where temporary files are stored. If the default temp directory can't be written to by the process running Dompdf you can specify a different directory. You can find details about the [Options in the wiki](https://github.com/dompdf/dompdf/wiki/Usage#options).

**Comment by KvRae** [comment]
I tried everything, but I still have the same issue. I have seen something on youtube about ignoring (commenting) a block of code in dompdf/image/cache.php and when I was looking for it inside the file I couldn't find it, some people told me that the problem might be from working on localhost, and others told me about something in dompdf latest version isn't stable ... Kinda lost and I don't know what to do now :(

**Comment by bsweeney** [comment]
Would love to know about code that appears to be unstable. If anyone says something like that to you feel free to send them on over here to post a bug report.

I don't see that I ever confirmed the version you have in use. Did you try enabling additional debug logging per the instructions in the wiki?

**Comment by KvRae** [comment]
Sir! I've caught an exception

 Aug  4 14:38:13 |CRITICA| REQUES Uncaught PHP Exception TypeError: "Argument 1 passed to Dompdf\FrameReflower\Text::layout_line() must be an instance of Dompdf\FrameDecorator\Block, null given, cal
led in C:\Users\karam\Desktop\Gestion Des Employees\GesEmp\vendor\dompdf\dompdf\src\FrameReflower\Text.php on line 399" at C:\Users\karam\Desktop\Gestion Des Employees\GesEmp\vendor\dompdf\dompdf\src\FrameReflow
er\Text.php line 263 
 
what's that mean and how to fix that?
Thank you

**Comment by bsweeney** [comment]
Looks like you're using an older version of Dompdf. An issue like that was fixed in #2125. Have you tried upgrading to a newer release.

**Comment by KvRae** [comment]
yes sir! and I still have this :
[Application] Aug  5 10:54:22 |CRITICA| REQUES Uncaught PHP Exception TypeError: "Argument 1 passed to Dompdf\FrameReflower\Text::layout_line() must be an instance of Dompdf\FrameDecorator\Block, null given, cal
led in C:\Users\karam\Desktop\Gestion Des Employees\GesEmp\vendor\dompdf\dompdf\src\FrameReflower\Text.php on line 399"
I really started to hate Symfony and PHP :(

**Comment by bsweeney** [comment]
Do you have a sample of the HTML + CSS that's generating this error?

**Comment by KvRae** [comment]
Im using: "dompdf/dompdf": "^2.0",
and for the HTML thing its in here: https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/templates/employees/avTravaux.html.twig

**Comment by bsweeney** [comment]
It hard for me to fully reproduce your HTML from a template. Better if you can provide the HTML that Dompdf is attempting to render, for example by calling `$dompdf->outputHtml()`.

**Comment by KvRae** [comment]
@bsweeney does dompdf support twig files?

**Comment by KvRae** [comment]
Sir to be specific 
I'm working on a Symfony 5.4 project,
here are the files that have a relation with the dompdf 
PdfService: the class that has all the config functionalities (options, parameters...):
[https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/src/Service/PdfService.php]
EmployeesController: this will create the instance, and calls the methods from the PdfService
[https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/src/Controller/EmployeesController.php]
avTravaux.html.twig: the HTML file generated, (I'm working with dynamic data that's why I'm using twig extension)[https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/templates/employees/avTravaux.html.twig]

**Comment by bsweeney** [comment]
Dompdf itself does not support twig, no. You might have a plug-in that leverages Dompdf to generate a PDF by rendering the HTML then passing that to Dompdf.

I do not use either symfony nor twig which is why I asked for the HTML. Can you provide the HTML of the rendered document?

**Comment by KvRae** [comment]
Then I don't know how this works not the way I want but it renders the pdf with data provided by the twig  
[HTML file rendered](https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/templates/employees/avTravaux.html.twig)

**Comment by bsweeney** [comment]
You could change [these lines](https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/src/Service/PdfService.php#L29-L31) from:

```
$this->domPdf->stream('service.pdf',[
    'Attachment' =>false
]);
```
to:
```
echo $this->domPdf->outputHtml();
```

Or even just echo the HTML after you [render the template](https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/src/Controller/EmployeesController.php#L91).

Also, I see you are calling both the [showPdfFile and generateBinaryPDF methods](https://github.com/KvRae/Tun-Telecom-Gesture-/blob/main/src/Controller/EmployeesController.php#L92-L93) from your PDF service. You should only call one of those methods. And the generate method isn't utilizing Dompdf correctly so you might just get rid of that one entirely.

**Comment by KvRae** [comment]
Thank you I'm working on it 
but for this one 
`echo $this->domPdf->outputHtml();`
it won't work, I should make a return statement of type response I guess that's why I made this one 

```
$this->domPdf->stream('service.pdf',[
    'Attachment' =>false
]);
```

**Comment by bsweeney** [comment]
I don't understand why that won't work. [`outputHtml`](https://github.com/dompdf/dompdf/blob/v2.0.0/src/Dompdf.php#L911-L919) just returns the HTML being parsed as a string, which you can echo out. That's not all that different from what the [`stream`](https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L4699-L4737) method does.

If you have to do something more than that because of your framework I believe you can figure out what that is.

**Comment by KvRae** [comment]
Yes ill try to make it my way if it doesn't work ill come back and try what you mentioned.
Thank you, sir, appreciate it

**Comment by KvRae** [comment]
Well, time to move on 
thank you sir @bsweeney for your effort
I appreciate it
